# Hello Tensors

In [7]:
# Prerequisites
import numpy as np
import tensorflow as tf

### Rank-0 Tensors (Scalars)

In [3]:
# NumPy
x = np.array(12)
print("NumPy Tensor: ", x)
print("The type of NumPy tensor: ", type(x))
print("The rank of NumPy tensor: ", x.ndim)
print("The shape of NumPy tensor: ", x.shape)
print("The data type of NumPy tensor: ", x.dtype)

# TensorFlow
t = tf.constant(42)
print("\nTensorFlow Tensor: ", t)
print("The type of TensorFlow tensor: ", type(t))
print("The rank of TensorFlow tensor: ", tf.rank(t).numpy())
print("The shape of TensorFlow tensor: ", t.shape)
print("The data type of TensorFlow tensor: ", t.dtype)


NumPy Tensor:  12
The type of NumPy tensor:  <class 'numpy.ndarray'>
The rank of NumPy tensor:  0
The shape of NumPy tensor:  ()
The data type of NumPy tensor:  int64

TensorFlow Tensor:  tf.Tensor(42, shape=(), dtype=int32)
The type of TensorFlow tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
The rank of TensorFlow tensor:  0
The shape of TensorFlow tensor:  ()
The data type of TensorFlow tensor:  <dtype: 'int32'>


### Rank-1 Tensors (Vectors)

In [4]:
x = np.array([1, 2, 7, 14, 25])
print("NumPy Tensor: ", x)
print("The type of NumPy tensor: ", type(x))
print("The rank of NumPy tensor: ", x.ndim)
print("The shape of NumPy tensor: ", x.shape)
print("The data type of NumPy tensor: ", x.dtype)

# TensorFlow
t = tf.constant([1, 2, 7, 14, 25])
print("\nTensorFlow Tensor: ", t)
print("The type of TensorFlow tensor: ", type(t))
print("The rank of TensorFlow tensor: ", tf.rank(t).numpy())
print("The shape of TensorFlow tensor: ", t.shape)
print("The data type of TensorFlow tensor: ", t.dtype)

NumPy Tensor:  [ 1  2  7 14 25]
The type of NumPy tensor:  <class 'numpy.ndarray'>
The rank of NumPy tensor:  1
The shape of NumPy tensor:  (5,)
The data type of NumPy tensor:  int64

TensorFlow Tensor:  tf.Tensor([ 1  2  7 14 25], shape=(5,), dtype=int32)
The type of TensorFlow tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
The rank of TensorFlow tensor:  1
The shape of TensorFlow tensor:  (5,)
The data type of TensorFlow tensor:  <dtype: 'int32'>


### Rank-2 Tensors (Matrices)

In [6]:
x = np.array([[5.0, 78, 6, 34, 10],
              [6.0, 79, 7, 35, 11],
              [7.0, 80, 8, 36, 12]])
print("NumPy Tensor: ", x)
print("The type of NumPy tensor: ", type(x))
print("The rank of NumPy tensor: ", x.ndim)
print("The shape of NumPy tensor: ", x.shape)
print("The data type of NumPy tensor: ", x.dtype)

# TensorFlow
t = tf.constant([[5.0, 78, 6, 34, 10],
                [6.0, 79, 7, 35, 11],
                [7.0, 80, 8, 36, 12]])
print("\nTensorFlow Tensor: ", t)
print("The type of TensorFlow tensor: ", type(t))
print("The rank of TensorFlow tensor: ", tf.rank(t).numpy())
print("The shape of TensorFlow tensor: ", t.shape)
print("The data type of TensorFlow tensor: ", t.dtype)

NumPy Tensor:  [[ 5. 78.  6. 34. 10.]
 [ 6. 79.  7. 35. 11.]
 [ 7. 80.  8. 36. 12.]]
The type of NumPy tensor:  <class 'numpy.ndarray'>
The rank of NumPy tensor:  2
The shape of NumPy tensor:  (3, 5)
The data type of NumPy tensor:  float64

TensorFlow Tensor:  tf.Tensor(
[[ 5. 78.  6. 34. 10.]
 [ 6. 79.  7. 35. 11.]
 [ 7. 80.  8. 36. 12.]], shape=(3, 5), dtype=float32)
The type of TensorFlow tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
The rank of TensorFlow tensor:  2
The shape of TensorFlow tensor:  (3, 5)
The data type of TensorFlow tensor:  <dtype: 'float32'>


### Rank-3 and higher order Tensors

In [7]:
x = np.array([[[5, 78, 6, 34, 10],
              [6, 79, 7, 35, 11],
              [7, 80, 8, 36, 12]],
             [[5, 78, 6, 34, 10],
              [6, 79, 7, 35, 11],
              [7, 80, 8, 36, 12]],
             [[5, 78, 6, 34, 10],
              [6, 79, 7, 35, 11],
              [7, 80, 8, 36, 12]]])
print("NumPy Tensor: ", x)
print("The type of NumPy tensor: ", type(x))
print("The rank of NumPy tensor: ", x.ndim)
print("The shape of NumPy tensor: ", x.shape)
print("The data type of NumPy tensor: ", x.dtype)

# TensorFlow
t = tf.ones(shape=(3, 3, 5))
print("\nTensorFlow Tensor: ", t)
print("The type of TensorFlow tensor: ", type(t))
print("The rank of TensorFlow tensor: ", tf.rank(t).numpy())
print("The shape of TensorFlow tensor: ", t.shape)
print("The data type of TensorFlow tensor: ", t.dtype)

NumPy Tensor:  [[[ 5 78  6 34 10]
  [ 6 79  7 35 11]
  [ 7 80  8 36 12]]

 [[ 5 78  6 34 10]
  [ 6 79  7 35 11]
  [ 7 80  8 36 12]]

 [[ 5 78  6 34 10]
  [ 6 79  7 35 11]
  [ 7 80  8 36 12]]]
The type of NumPy tensor:  <class 'numpy.ndarray'>
The rank of NumPy tensor:  3
The shape of NumPy tensor:  (3, 3, 5)
The data type of NumPy tensor:  int64

TensorFlow Tensor:  tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)
The type of TensorFlow tensor:  <class 'tensorflow.python.framework.ops.EagerTensor'>
The rank of TensorFlow tensor:  3
The shape of TensorFlow tensor:  (3, 3, 5)
The data type of TensorFlow tensor:  <dtype: 'float32'>


### NumPy Matirx/Tensor Reshaping

In [8]:
x = np.array([[0., 1.],
                [2., 3.],
                [4., 5.]])
print("The shape of NumPy tensor: ", x.shape)

The shape of NumPy tensor:  (3, 2)


In [10]:
# Reshape
x = x.reshape(6, 1)
print("NumPy Tensor:\n", x)
print("The shape of NumPy tensor: ", x.shape)

NumPy Tensor:
 [[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
The shape of NumPy tensor:  (6, 1)


In [11]:
# Reshape
x = x.reshape(2, 3)
print("NumPy Tensor:\n", x)
print("The shape of NumPy tensor: ", x.shape)

NumPy Tensor:
 [[0. 1. 2.]
 [3. 4. 5.]]
The shape of NumPy tensor:  (2, 3)


In [12]:
x = np.zeros((40, 200))
print("The shape of NumPy tensor: ", x.shape)
x = np.transpose(x)
print("Shape after transpose: ", x.shape)


The shape of NumPy tensor:  (40, 200)
Shape after transpose:  (200, 40)


### TensorFlow Tensors are not assignable, use tf.variable() for assignments

In [13]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.5439271],
       [ 0.9365572],
       [-1.5859779]], dtype=float32)>


In [15]:
# Assign to variable tensor
v.assign(tf.ones((3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [16]:
# One can also assign to invidual elements
v[0, 0].assign(2.)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[2.],
       [1.],
       [1.]], dtype=float32)>


assign_add() and assign_sub() correspond to += and -= 

In [18]:
v.assign_add(tf.ones((3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [2.],
       [2.]], dtype=float32)>


### TensorFlow Math

In [27]:
a = tf.constant([[1., 2.],[3., 4.]])
print("a = ", a)
b = tf.square(a)
print("b = ", b)
c = tf.sqrt(a)
print("c = ", c)
d = a + c
print("d = ", d)
e = tf.matmul(a, c)
print("e = ", e)
e *= a
print("e = ", e)

a =  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
b =  tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
c =  tf.Tensor(
[[1.        1.4142135]
 [1.7320508 2.       ]], shape=(2, 2), dtype=float32)
d =  tf.Tensor(
[[2.        3.4142137]
 [4.732051  6.       ]], shape=(2, 2), dtype=float32)
e =  tf.Tensor(
[[ 4.464102   5.4142137]
 [ 9.928204  12.2426405]], shape=(2, 2), dtype=float32)
e =  tf.Tensor(
[[ 4.464102 10.828427]
 [29.78461  48.970562]], shape=(2, 2), dtype=float32)


### GradientTape

Use GradientTape to get gradient

In [28]:
input = tf.Variable(initial_value=73.)
with tf.GradientTape() as tape:
    result = tf.square(input)

gradient = tape.gradient(result, input)
print("Gradient = ", gradient)

Gradient =  tf.Tensor(146.0, shape=(), dtype=float32)


Using GradientTape with constant tensor inputs.  Need to use watch() to have the variable monitored

In [30]:
input_const = tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result = tf.square(input_const)
gradient = tape.gradient(result, input_const)
print("Gradient = ", gradient)

Gradient =  tf.Tensor(6.0, shape=(), dtype=float32)


Using nested gradient tapes to compute second-order gradients

In [31]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position = 4.9 * time ** 2
    speed = inner_tape.gradient(position, time)
acceleration = outer_tape.gradient(speed, time)
print("Acceleration = ", acceleration)

Acceleration =  tf.Tensor(9.8, shape=(), dtype=float32)


## Image Tensors

In [8]:
from sklearn.datasets import load_sample_images

images = load_sample_images()["images"]
images = tf.keras.layers.CenterCrop(height=70, width=120)(images)
images = tf.keras.layers.Rescaling(scale = 1/ 255)(images)

In [10]:
print("images type: ", type(images))
print("image tensor shape: ", images.shape)

images type:  <class 'tensorflow.python.framework.ops.EagerTensor'>
image tensor shape:  (2, 70, 120, 3)
