# Hello Tensors

In [1]:
# Prerequisites
import numpy as np

### Rank-0 Tensors (Scalars)

In [2]:
x = np.array(12)
print("Tensor: ", x)
print("The type of tensor: ", type(x))
print("The rank of tensor: ", x.ndim)
print("The shape of tensor: ", x.shape)
print("The data type of tensor: ", x.dtype)

Tensor:  12
The type of tensor:  <class 'numpy.ndarray'>
The rank of tensor:  0
The shape of tensor:  ()
The data type of tensor:  int64


### Rank-1 Tensors (Vectors)

In [3]:
x = np.array([1, 2, 7, 14, 25])
print("Tensor: ", x)
print("The type of tensor: ", type(x))
print("The rank of tensor: ", x.ndim)
print("The shape of tensor: ", x.shape)
print("The data type of tensor: ", x.dtype)

Tensor:  [ 1  2  7 14 25]
The type of tensor:  <class 'numpy.ndarray'>
The rank of tensor:  1
The shape of tensor:  (5,)
The data type of tensor:  int64


### Rank-2 Tensors (Matrices)

In [4]:
x = np.array([[5.0, 78, 6, 34, 10],
              [6.0, 79, 7, 35, 11],
              [7.0, 80, 8, 36, 12]])
print("Tensor:\n", x)
print("The type of tensor: ", type(x))
print("The rank of tensor: ", x.ndim)
print("The shape of tensor: ", x.shape)
print("The data type of tensor: ", x.dtype)

Tensor:
 [[ 5. 78.  6. 34. 10.]
 [ 6. 79.  7. 35. 11.]
 [ 7. 80.  8. 36. 12.]]
The type of tensor:  <class 'numpy.ndarray'>
The rank of tensor:  2
The shape of tensor:  (3, 5)
The data type of tensor:  float64


### Rank-3 and higher order Tensors

In [5]:
x = np.array([[[5, 78, 6, 34, 10],
              [6, 79, 7, 35, 11],
              [7, 80, 8, 36, 12]],
             [[5, 78, 6, 34, 10],
              [6, 79, 7, 35, 11],
              [7, 80, 8, 36, 12]],
             [[5, 78, 6, 34, 10],
              [6, 79, 7, 35, 11],
              [7, 80, 8, 36, 12]]])
print("Tensor:\n", x)
print("The type of tensor: ", type(x))
print("The rank of tensor: ", x.ndim)
print("The shape of tensor: ", x.shape)
print("The data type of tensor: ", x.dtype)

Tensor:
 [[[ 5 78  6 34 10]
  [ 6 79  7 35 11]
  [ 7 80  8 36 12]]

 [[ 5 78  6 34 10]
  [ 6 79  7 35 11]
  [ 7 80  8 36 12]]

 [[ 5 78  6 34 10]
  [ 6 79  7 35 11]
  [ 7 80  8 36 12]]]
The type of tensor:  <class 'numpy.ndarray'>
The rank of tensor:  3
The shape of tensor:  (3, 3, 5)
The data type of tensor:  int64


### Tensor Reshaping

In [6]:
x = np.array([[0., 1.],
                [2., 3.],
                [4., 5.]])
print("The shape of tensor: ", x.shape)

The shape of tensor:  (3, 2)


In [7]:
# Reshape
x = x.reshape(6, 1)
print("Tensor:\n", x)
print("The shape of tensor: ", x.shape)

Tensor:
 [[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
The shape of tensor:  (6, 1)


In [8]:
# Reshape
x = x.reshape(2, 3)
print("Tensor:\n", x)
print("The shape of tensor: ", x.shape)

Tensor:
 [[0. 1. 2.]
 [3. 4. 5.]]
The shape of tensor:  (2, 3)


### Transpose

In [10]:
x = np.zeros((40, 200))
print("The shape of tensor: ", x.shape)
x = np.transpose(x)
print("Shape after transpose: ", x.shape)


The shape of tensor:  (40, 200)
Shape after transpose:  (200, 40)
